### ISSUE TITLE
missing default types

### ISSUE THREAD

**Issue by AdrienLemaire** [muhammadsammy/tailwindcss-classnames#48]
Related to #15 where you fixed the default color type.

```
 TS2345: Argument of type '"transition"' is not assignable to  parameter of type 'TArg'
```

I am not setting transition in my config, because [it's recommended](https://tailwindcss.com/docs/configuration).

> Every section of the config file is optional, so you only have to specify what you'd like to change. Any missing sections will fall back to Tailwind's default configuration.
> For most users we encourage you to keep your config file as minimal as possible, and only specify the things you want to customize.

And the [transition doc](https://tailwindcss.com/docs/transition-property) shows the **transition** property, but tailwindscss-classnames generates the following types:
```ts
export type TTransitionProperty = 
  | 'transition-none'
  | 'transition-all'
  | 'transition-default'
  | 'transition-colors'
  | 'transition-opacity'
  | 'transition-shadow'
  | 'transition-transform';
```
both `transition` and `transition-default` should be in the type.

From the [theme configuration](https://tailwindcss.com/docs/theme), I see

> You'll notice that using a key of default in the theme configuration created the class rounded with no suffix. This is a common convention in Tailwind supported by many (although not all) of the core plugins.

The fact that it's not supported by all core plugins is annoying, Maybe you can manage a blacklist of plugins, and auto-add the no-suffix type for all plugins not listed in that blacklist?

**Comment by muhammadsammy** [comment]
> 
> both `transition` and `transition-default` should be in the type.
> 
> From the [theme configuration](https://tailwindcss.com/docs/theme), I see
> 
> > You'll notice that using a key of default in the theme configuration created the class rounded with no suffix. This is a common convention in Tailwind supported by many (although not all) of the core plugins.
> 
> The fact that it's not supported by all core plugins is annoying, Maybe you can manage a blacklist of plugins, and auto-add the no-suffix type for all plugins not listed in that blacklist?
>
The missing `transition` type has been added. I could remove the `default` suffix from all types, but this will not be correct for other classes that have the `default` suffix, so I've opened a [discussion](https://github.com/tailwindlabs/tailwindcss/discussions/2367) on thier repo asking about this.

**Comment by muhammadsammy** [comment]
The CLI now removes `default` suffix from all types except those I know to have it (*cursor-default). 
Classes of transition property don't seem to be keeping the `default` suffix because the value of [default key in `transitionProperty`](https://github.com/tailwindlabs/tailwindcss/blob/0221f2f003875fde44395cecc12cca61b5168231/stubs/defaultConfig.stub.js#L606) in the default tailwind config is the same as for the [`.transition` class](https://tailwindcss.com/docs/transition-property).

I will add more [here](https://github.com/muhammadsammy/tailwindcss-classnames/blob/845b9bc12a640a3709b7c596bf7c8ca55064464b/src/cli/utils/index.ts#L10) once they list those to have the suffix.
If you know any specific classnames that keep the default suffix, please create a PR!

**Comment by muhammadsammy** [comment]
This issue has been resolved by using 'DEFAULT' for classes that does not have the suffix and using 'default' to kepp the suffix in the classname (https://github.com/tailwindlabs/tailwindcss/pull/2580)

Which is covered by this PR #70
